### ISSUE TITLE
my code?

### ISSUE THREAD

**Issue by budaLi** [lovelyPig-alt/Simple_interface_test#2]
my code?

**Comment by lovelyPig-alt** [comment]
Yes, I learned from it



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lovelyPig-alt/Simple_interface_test"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 中午11:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lovelyPig-alt/Simple_interface_test] my code? (Issue #2)





 
my code?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by budaLi** [comment]
ok fine
